# -*- coding: utf-8 -*-
"""Stock_Valuation_Automated

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUAtiSzW4GebLMzAjqES_0ubqauZxA--
"""

# ==============================================================================
# CELL 1: SETUP & INTERACTIVE RUNTIME ARGUMENTS
# ==============================================================================
# Install required packages quietly
!pip install -q yfinance tabulate

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tabulate import tabulate
import warnings

warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
sns.set_palette("crest")

# ------------------------------------------------------------------------------
# INTERACTIVE CONTROL PANEL (Colab Forms)
# ------------------------------------------------------------------------------
# @markdown Enter the target stock ticker (e.g., AAPL, TATASTEEL.NS, BORORENEW.NS):
TARGET_TICKER = "BORORENEW.NS" # @param {type:"string"}

# @markdown Override the default Cost of Capital / WACC (Enter 0.0 to auto-calculate):
WACC_OVERRIDE = 0.18 # @param {type:"number"}

# @markdown Base case projected Year 1-5 Revenue CAGR (e.g., 0.08 for 8%):
GROWTH_RATE = 0.10 # @param {type:"number"}

# @markdown Target normalized operating margin (e.g., 0.18 for 18%):
TARGET_MARGIN = 0.18 # @param {type:"number"}

print(f"✅ Cell 1 Complete: Environment configured for {TARGET_TICKER}.")

"""# Data **Retrieval**"""

# ==============================================================================
# CELL 2: DATA INGESTION & PEER DISCOVERY
# ==============================================================================

DEFAULT_PEERS = ["MSFT", "AAPL", "GOOGL", "AMZN"]
INDIA_DEFAULT_PEERS = ["RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS"]

def fetch_universal_data(ticker_symbol):
    print(f"[INFO] Initializing pipeline ingestion for core asset: {ticker_symbol}")
    ticker = yf.Ticker(ticker_symbol)
    try:
        info = ticker.info
        if not info or 'currentPrice' not in info:
            raise ValueError(f"Ticker '{ticker_symbol}' returned no active market data.")
        financials = ticker.financials
        balance_sheet = ticker.balance_sheet
        history = ticker.history(period="5y")
        return ticker, financials, balance_sheet, info, history
    except Exception as e:
        print(f"[CRITICAL] Data extraction failed: {e}")
        return None, None, None, None, None

def discover_competitors(target_info, ticker_symbol):
    print("[INFO] Executing dynamic sector peer discovery...")
    is_india = ticker_symbol.upper().endswith(".NS") or ticker_symbol.upper().endswith(".BO")
    industry = target_info.get('industry', 'Unknown')
    sector = target_info.get('sector', 'Unknown')
    print(f"[INFO] Profile Identified -> Sector: {sector} | Industry: {industry}")

    # Heuristic mapping for standard global industries
    if "Steel" in industry:
        return ["JSWSTEEL.NS", "SAIL.NS", "HINDALCO.NS"] if is_india else ["X", "NUE", "CLF"]
    elif "Solar" in industry or "Renewable" in sector:
        return ["BOROLTD.NS", "INSOLATION.NS", "WEBELSOLAR.NS"] if is_india else ["FSLR", "ENPH", "SEDG"]
    elif "Technology" in sector or "Software" in industry:
        return ["TCS.NS", "INFY.NS", "WIT.NS"] if is_india else ["MSFT", "GOOGL", "META"]
    elif "Bank" in industry:
        return ["ICICIBANK.NS", "SBIN.NS", "AXISBANK.NS"] if is_india else ["JPM", "BAC", "C"]

    return INDIA_DEFAULT_PEERS if is_india else DEFAULT_PEERS

print("✅ Cell 2 Complete: Ingestion and discovery functions loaded.")

"""# **DCF Valuation Engine and Relative** **Valuation**"""

# ==============================================================================
# CELL 3: FINANCIAL MATH (DCF & COMPS)
# ==============================================================================

def run_flexible_dcf(info, growth_rate, op_margin, calculated_wacc):
    current_price = info.get('currentPrice', 100)
    shares = info.get('sharesOutstanding', 1e8)
    rev_base = info.get('totalRevenue', 10e9)
    debt = info.get('totalDebt', 0)
    cash = info.get('totalCash', 0)

    # Standardized reinvestment heuristics
    tax_rate = 0.25
    capex_drag = 0.08
    depr_add = 0.05
    nwc_drag = 0.07
    terminal_growth = 0.045 if calculated_wacc > 0.10 else 0.03

    years = [f"Year {i}" for i in range(1, 6)]
    forecast = pd.DataFrame(index=['Revenue', 'EBIT', 'NOPAT', 'Free Cash Flow (FCF)'], columns=years)

    prev_rev = rev_base
    for year in years:
        rev = prev_rev * (1 + growth_rate)
        ebit = rev * op_margin
        nopat = ebit * (1 - tax_rate)
        fcf = nopat + (rev * depr_add) - (rev * capex_drag) - ((rev - prev_rev) * nwc_drag)

        forecast.loc['Revenue', year] = rev
        forecast.loc['EBIT', year] = ebit
        forecast.loc['NOPAT', year] = nopat
        forecast.loc['Free Cash Flow (FCF)', year] = fcf
        prev_rev = rev

    discount_factors = [1 / ((1 + calculated_wacc) ** i) for i in range(1, 6)]
    fcf_arr = forecast.loc['Free Cash Flow (FCF)'].values.astype(float)
    pv_fcf = fcf_arr * discount_factors

    tv = (fcf_arr[-1] * (1 + terminal_growth)) / (calculated_wacc - terminal_growth)
    pv_tv = tv / ((1 + calculated_wacc) ** 5)

    ev = np.sum(pv_fcf) + pv_tv
    equity_val = ev + cash - debt
    intrinsic_value = equity_val / shares

    upside = (intrinsic_value / current_price) - 1
    return intrinsic_value, upside, forecast

def run_relative_comps(peer_list):
    rows = []
    for symbol in peer_list:
        try:
            t = yf.Ticker(symbol)
            info = t.info
            rows.append({
                'Peer Ticker': symbol,
                'P/E': info.get('trailingPE', np.nan),
                'EV/EBITDA': info.get('enterpriseToEbitda', np.nan),
                'P/Sales': info.get('priceToSalesTrailing12Months', np.nan)
            })
        except:
            continue
    return pd.DataFrame(rows).set_index('Peer Ticker')

print("✅ Cell 3 Complete: DCF and Comps mathematics established.")

"""# **Visualization and Performance Dashboard**"""

# ==============================================================================
# CELL 4: EXECUTION & INSTITUTIONAL DASHBOARD
# ==============================================================================

# 1. Pipeline Ingestion
ticker_str = TARGET_TICKER.upper()
ticker_obj, financials, balance_sheet, info, history = fetch_universal_data(ticker_str)

if ticker_obj:
    # 2. Dynamic WACC Hurdles
    if WACC_OVERRIDE > 0:
        wacc_hurdle = WACC_OVERRIDE
    else:
        # Base hurdle rate proxy based on operational geography
        wacc_hurdle = 0.115 if ticker_str.endswith(".NS") or ticker_str.endswith(".BO") else 0.085

    # 3. Operations
    peers = discover_competitors(info, ticker_str)
    val_base, upside_base, sheet_base = run_flexible_dcf(info, GROWTH_RATE, TARGET_MARGIN, wacc_hurdle)
    val_bull, _, _ = run_flexible_dcf(info, GROWTH_RATE + 0.08, TARGET_MARGIN + 0.05, wacc_hurdle)
    val_bear, _, _ = run_flexible_dcf(info, max(0.02, GROWTH_RATE - 0.05), max(0.06, TARGET_MARGIN - 0.06), wacc_hurdle)
    comps_df = run_relative_comps(peers)

    # 4. Text Reporting
    print("\n" + "="*85)
    print(f"         AUTOMATED INSTITUTIONAL EXECUTIVE REPORT OUTLINE: {ticker_str}")
    print("="*85)

    currency = "₹" if (ticker_str.endswith(".NS") or ticker_str.endswith(".BO")) else "$"
    rating = "STRONG BUY" if upside_base > 0.25 else "BUY" if upside_base > 0.05 else "HOLD" if upside_base >= -0.10 else "UNDERPERFORM"

    metrics = [
        ["Asset Profile Short Name", info.get('shortName', ticker_str)],
        ["Current Traded Market Price", f"{currency}{info.get('currentPrice', 0):,.2f}"],
        ["Model Base Case Intrinsic Target", f"{currency}{val_base:,.2f}"],
        ["Optimistic Target (Bull Scenario)", f"{currency}{val_bull:,.2f}"],
        ["Pessimistic Target (Bear Scenario)", f"{currency}{val_bear:,.2f}"],
        ["Implied Margin Gap Return", f"{upside_base:.1%}"],
        ["Algorithmic Execution Rating", f"*** {rating} ***"]
    ]
    print(tabulate(metrics, headers=["Valuation Parameter", "Calculated Output"], tablefmt="fancy_grid"))
    print("\n" + "-"*40 + "\nCOMPETITIVE MULTIPLES BENCHMARKS\n" + "-"*40)
    print(tabulate(comps_df, headers='keys', tablefmt='psql'))

    # 5. Visual Dashboard
    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    fig.suptitle(f"Valuation Analytics Overview: {ticker_str}", fontsize=16, weight='bold', color='#1e4247')

    # Plot A: Price History
    axes[0].plot(history.index, history['Close'], color='teal', linewidth=2)
    axes[0].set_title("5-Year Price History", weight='bold')
    axes[0].set_ylabel(f"Price ({currency})")

    # Plot B: Projected FCF
    rev_years = sheet_base.columns
    fcf_projections = sheet_base.loc['Free Cash Flow (FCF)'].values
    axes[1].bar(rev_years, fcf_projections, color='#4ba3a5')
    axes[1].set_title("Forward Unlevered Free Cash Flow", weight='bold')

    # Plot C: Cross-Scenario Spectrum
    scenarios = ['Bear Target', 'Current Price', 'Base Target', 'Bull Target']
    values = [val_bear, info.get('currentPrice', 0), val_base, val_bull]
    colors = ['#c27c7c', '#727878', '#498c8f', '#297850']
    axes[2].bar(x=scenarios, height=values, color=colors)
    axes[2].set_title("Cross-Scenario Valuation vs Market", weight='bold')

    plt.tight_layout()
    plt.show()